In [1]:
import numpy as np

In [18]:
def calculate(list):
    try:
            x = np.array(list).reshape(3,3)
            x_f = x.flatten()
            calculations = {
                'mean': [np.mean(x, axis=0), np.mean(x, axis=1), np.mean(x_f)],
                'variance':[np.var(x, axis=0), np.var(x, axis=1), np.var(x_f)],
                'standard deviation':[np.std(x, axis=0), np.std(x, axis=1), np.std(x_f)],
                'max':[np.max(x, axis=0), np.max(x, axis=1), np.max(x_f)],
                'min':[np.min(x, axis=0), np.min(x, axis=1), np.min(x_f)],
                'sum':[np.sum(x, axis=0), np.sum(x, axis=1), np.sum(x_f)]
            }
            return calculations
        
    
    except ValueError:
        print('List must contain nine numbers')





        
   

In [19]:
calculate([0,1,2,3,4,5,6,7,8])

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}

In [21]:
calculate([10,11,12,13,14,15,16,17,18])

{'mean': [array([13., 14., 15.]), array([11., 14., 17.]), 14.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([16, 17, 18]), array([12, 15, 18]), 18],
 'min': [array([10, 11, 12]), array([10, 13, 16]), 10],
 'sum': [array([39, 42, 45]), array([33, 42, 51]), 126]}

In [20]:
calculate([0,1,2,3,4,5,6,7])

List must contain nine numbers
